[DEPO]
# Depo Sheet = Filter kode
MGL Shell = MGL
SL Shell = SL
YY Shell = YY
SMG Shell = SMG, SG
TGL Shell = TGL
PWT Shell = PW, PWT
Pati Shell = PA
KDI Shell = KDI-0, KDI-1, KDI-4
KDI Ban = KDI-2, KDI-3
KDI Top 1 = KDI-5
KDI Osram = KDI-6
MKS Shell = MKS-1, MKS-2, MKS-3, MKS-5
MKS Ban= MKS-4
MKS Osram = MKS-6
Palu Shell = PLU

[SETTINGS]
# Divisi untuk Nomor Pelanggan yang diawali angka 1-9
DIGIT_DEFAULT_DEPO = Ban

[SPLIT]
# Pivot Hasil
Ban	=	Ban Jawa
MGL Shell	=	Selatan
SL Shell	=	Selatan
YY Shell	=	Selatan
SMG Shell	=	Utara
TGL Shell	=	Utara
PWT Shell	=	Utara
Pati Shell	=	Utara
KDI Shell	=	Sulawesi Shell
KDI Ban	=	Sulawesi Ban
KDI Top 1	=	Sulawesi Top 1
KDI Osram	=	Sulawesi Osram
MKS Shell	=	Sulawesi Shell
MKS Ban	=	Sulawesi Ban
MKS Osram	=	Sulawesi Osram
Palu Shell	=	Sulawesi Shell
